### PR TITLE
fix CharReaderFromSyncStream read characters less than chunkSize (#2108)

### LINKED ISSUE #2108: Unexpected results with CharReaderFromSyncStream when chunk size is less than reading count
I suggest buffering up only inside the `tempStringBuilder.length < count` block after checking if more buffer is needed, rather than before. I will work on it and send a PR.

#### Test case
```kotlin
val reader = "áéíóúñ".toByteArray(UTF8).toCharReader(charset = UTF8, chunkSize = 2)
assertEquals("á,éí,óúñ", listOf(reader.read(1), reader.read(2), reader.read(10)).joinToString(","))
```

Expected : `á,éí,óúñ`
Actual   : `á,é,í`

### PR DESCRIPTION
**Pull request by itboy87**
There was an issue with `CharReaderFromSyncStream`. When attempting to read characters fewer than the specified `chunkSize`, it returns the maximum `chunkSize` data instead. I have set a minimum `chunkSize` limit to 8 because the decoder requires a minimum size of the maximum character size to decode. I believe the maximum character size in bytes is 4 bytes, but for safety, I used 8 bytes. Therefore, if anyone sets the chunkSize to less than 8, it will throw an exception.

* Created two new constants:
```kotlin
companion object {
       private const val DEFAULT_CHUNK_SIZE = 1024
       private const val MIN_CHUNK_SIZE = 8
}
```

* Check `chunkSize` and throw `IllegalArgumentException` exception if its less than `MIN_CHUNK_SIZE`
```kotlin
init {
  if (chunkSize < MIN_CHUNK_SIZE) throw IllegalArgumentException("chunkSize must be greater than $MIN_CHUNK_SIZE")
}
```

* Refactored buffer fill code to `bufferUp()` function. This function returns the number of bytes added to the buffer. If `tempStringBuilder` doesn't have enough characters to read, the function will attempt to read more into the buffer until the condition is met or the stream is empty.

This PR closes #2108

### CODE REVIEW

File: korge-core/test/korlibs/io/net/URLTest.kt [hunk 1]
```diff
@@ -115,6 +115,18 @@ class URLTest {
...
+        assertEquals("https", url3.scheme)
+        assertEquals("username:password", url3.userInfo)
+        assertEquals("username", url3.user)
+        assertEquals("password", url3.password)
+        assertEquals("example.com", url3.host)
+        assertEquals(8443, url3.port)
+        assertEquals("/path/to/resource", url3.path)
+        assertEquals("/path/to/resource?q=1", url3.pathWithQuery)
+        assertEquals("q=1", url3.query)
+        assertEquals("https://username:password@example.com:8443/path/to/resource?q=1", url3.fullUrl)
```
Comment (soywiz) [inline korge-core/test/korlibs/io/net/URLTest.kt:129]: I guess this should be part of another PR

File: korge-core/src/korlibs/io/stream/CharReader.kt [hunk 2]
```diff
@@ -13,33 +13,50 @@ fun ByteArray.toCharReader(charset: Charset, chunkSize: Int = 1024): CharReader
...
     CharReaderFromSyncStream(this, charset, chunkSize)
 
-class CharReaderFromSyncStream(val stream: SyncStream, val charset: Charset, val chunkSize: Int = 1024) : CharReader {
+class CharReaderFromSyncStream(val stream: SyncStream, val charset: Charset, val chunkSize: Int = DEFAULT_CHUNK_SIZE) : CharReader {
     private val temp = ByteArray(chunkSize)
     private val buffer = ByteArrayDeque()
     private var tempStringBuilder = StringBuilder()
 
+    init {
+        if (chunkSize < MIN_CHUNK_SIZE) throw IllegalArgumentException("chunkSize must be greater than $MIN_CHUNK_SIZE")
```
Comment (soywiz) [inline korge-core/src/korlibs/io/stream/CharReader.kt:22]: Really minor an optional, but: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require.html

**Review by soywiz — CHANGES_REQUESTED** [review]
URLText extra test should be done in a separate PR since it looks unrelated to this

**Comment by itboy87** [comment]
@soywiz ok i will update it.

File: korge-core/test/korlibs/io/net/URLTest.kt (hunk 1 above)
Comment (itboy87) [reply korge-core/test/korlibs/io/net/URLTest.kt:129]: ok i will add that in PR for fixing URL `subScheme`

File: korge-core/src/korlibs/io/stream/CharReader.kt (hunk 2 above)
Comment (itboy87) [reply korge-core/src/korlibs/io/stream/CharReader.kt]: Done replaced with `require`

File: korge-core/test/korlibs/io/net/URLTest.kt (hunk 1 above)
Comment (itboy87) [reply korge-core/test/korlibs/io/net/URLTest.kt]: Done moved to another PR.

**Review by soywiz — APPROVED** [review]
LGTM

**Comment by soywiz** [comment]
Thanks!
